app/models.py
from app import db

class Record(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.String(50), nullable=False)

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO # type: ignore

socketio = SocketIO()

def create_app():
    app = Flask(__name__)
    app.secret_key = 'your_secret_key'
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/main')
    socketio.init_app(app)
    return app,socketio

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
import os
from flask import render_template, session, request, redirect, url_for, Blueprint
from datetime import datetime
from PIL import ImageDraw, ImageFont, Image
import pytz
import os
import base64
from . import main
from app import socketio

UPLOAD_FOLDER = 'path/to/storage'
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

def update_content():
    socketio.emit('refresh', {'data: New content'}, broadcast=True)
    return "Nội dung mới đã được update"

@main.route('/')
def index():
    qr_creation_time = session.get('qr_creation_time', None)
    return render_template('index.html', qr_creation_time=qr_creation_time)

@main.route('/about')
def about():
    return render_template('about.html')

def generate_qr(url, timestamp, model, quantity):
    from PIL import Image, ImageDraw, ImageFont
    import qrcode

    canvas_width, canvas_height = 645, 645  # tăng chiều cao thêm
    qr_size = 300

    # Tạo QR code
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=8,
        border=4,
    )
    qr.add_data(url)
    qr.make(fit=True)
    qr_img = qr.make_image(fill_color="black", back_color="white").convert('RGB')
    qr_img = qr_img.resize((qr_size, qr_size), Image.Resampling.LANCZOS)

    # Tạo canvas
    canvas = Image.new("RGB", (canvas_width, canvas_height), "white")
    qr_position = ((canvas_width - qr_size) // 2, 10)
    canvas.paste(qr_img, qr_position)
    return canvas



@main.route('/generate_qr_download')
def generate_qr_download():
    model = request.args.get('model', 'UnknownModel')
    quantity = request.args.get('quantity', '0')
    timestamp = datetime.now(pytz.timezone('Asia/Ho_Chi_Minh'))
    creation_time_str = timestamp.strftime('%Y-%m-%d %H:%M:%S')
    formatted_timestamp = timestamp.strftime('%Y%m%d%H%M%S')
    url = f"https://pavonine-qrcode-1.onrender.com/main/scan_qr/{formatted_timestamp}?model={model}&quantity={quantity}"
    qr_name = f'Pavonine_{formatted_timestamp}.png'
    qr_path = os.path.join(UPLOAD_FOLDER, qr_name)
    image = generate_qr(url, formatted_timestamp, model, quantity)
    image.save(qr_path, format="PNG")
    session['qr_creation_time'] = formatted_timestamp
    session['qr_image_path'] = qr_path
    return redirect(url_for('main.qr_info', model=model, quantity=quantity,creation_time_str=creation_time_str))


@main.route('/qr_info')
def qr_info():
    qr_image_path = session.get('qr_image_path')
    creation_time_str = request.args.get("creation_time_str",'Unknow')
    data = request.args.get('data')
    model = request.args.get('model', 'UnknownModel')
    quantity = request.args.get('quantity', '0')
    qr_name = os.path.basename(qr_image_path) if qr_image_path else None
    if not qr_image_path or not creation_time_str:
        return "QR code not found", 404

    with open(qr_image_path, "rb") as img_file:
        qr_image_base64 = base64.b64encode(img_file.read()).decode('utf-8')

    return render_template(
    'qr_info.html',
    qr_image=qr_image_base64,
    creation_time_str=creation_time_str,
    qr_name=qr_name,
    data=data,
    model=model,
    quantity=quantity
)


@main.route('/scan_qr/<timestamp>')
def scan_qr(timestamp):
    model = request.args.get('model', 'UnknownModel')
    quantity = request.args.get('quantity', '0')
    status = "OK"
    if not timestamp:
        return render_template('scan_qr.html', message="Timestamp is missing in the URL.", data=None)
    scan_time = datetime.now(pytz.timezone('Asia/Ho_Chi_Minh'))

    if "9A" in model:
        tz = pytz.timezone('Asia/Ho_Chi_Minh')
        creation_qr = tz.localize(datetime.strptime(timestamp, '%Y%m%d%H%M%S'))
        creation_time_str = creation_qr.strftime('%Y-%m-%d %H:%M:%S')
        message = """🔍 Thông tin mã QR như sau:<br>"""
    elif "BN61" in model:
        tz = pytz.timezone('Asia/Ho_Chi_Minh')
        creation_qr = tz.localize(datetime.strptime(timestamp, '%Y%m%d%H%M%S'))
        creation_time_str = creation_qr.strftime('%Y-%m-%d %H:%M:%S')
        message = """🔍 Thông tin mã QR như sau:<br>"""
    else:
        try:
            tz = pytz.timezone('Asia/Ho_Chi_Minh')
            creation_qr = tz.localize(datetime.strptime(timestamp, '%Y%m%d%H%M%S'))
            creation_time_str = creation_qr.strftime('%Y-%m-%d %H:%M:%S')
            time_diff = scan_time - creation_qr
            time_diff_hours = time_diff.total_seconds() / 3600
            time_diff_minutes = time_diff.total_seconds() / 60

            if time_diff_hours > 12:
                message = """✅ Mã QR đã đủ 12 giờ. Vui lòng chuyển công đoạn tiếp theo.<br>✅ QR 코드 생성 후 12시간이 지났습니다. 다음 단계로 진행해 주세요."""
            else:
                remaining_hours = 11 - int(time_diff_hours)
                remaining_minutes = 60 - int(time_diff_minutes % 60)
                message = f"""⏳ Mã QR chưa đủ 12 giờ. Vui lòng đợi thêm {remaining_hours} giờ: {remaining_minutes} phút.<br>⏳ QR 코드 생성 후 12시간이 아직 지나지 않았습니다. {remaining_hours}시간 {remaining_minutes}분 더 기다려 주세요."""
        except ValueError:
            creation_time_str = None
            message = "❌ Mã QR bị lỗi. Vui lòng tạo lại mã QR.<br>❌ QR 코드에 오류가 있습니다. QR 코드를 다시 생성해 주세요."

    

    return render_template(
    'scan_qr.html',
    creation_time_str=creation_time_str,
    message=message,
    data=timestamp,
    model=model,
    quantity=quantity,
    status = status

)

app/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/about')
def about():
    return render_template('about.html')

app/templates/about.html
{% extends 'layout.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h2>About Us</h2>
    <p>This page contains information about us.</p>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}

{% block title %}PAVONINE VINA{% endblock %}

{% block content %}
        <div class="slider">
            <div class="slides">
                <img src="{{ url_for('static', filename='images/Total.jpg') }}" alt="Image 1">
                <img src="{{ url_for('static', filename='images/Press.jpg') }}" alt="Image 2">
                <img src="{{ url_for('static', filename='images/MC.jpg') }}" alt="Image 3">
                <img src="{{ url_for('static', filename='images/MC_NG.jpg') }}" alt="Image 5">
                <img src="{{ url_for('static', filename='images/HairLine.jpg') }}" alt="Image 4">
                <img src="{{ url_for('static', filename='images/Anodizing.jpg') }}" alt="Image 6">
                <img src="{{ url_for('static', filename='images/Assembly.jpg') }}" alt="Image 7">
            </div>
        </div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PAVONINE VINA{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon/house.png')}}" type="image/png">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
    <script src="{{ url_for('static', filename='js/scripts.js') }}" defer></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.0/socket.io.min.js"></script>
</head>
<body>
    <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbarheader">
                <a class="navbar-brand" href="{{ url_for('main.index') }}"><i class="fa fa-home" aria-hidden="true"></i></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item">
                        <a class="nav-link alink" href="{{ url_for('main.index') }}">PAVONINE</a>
                      </li>
                      <!--<li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">Press</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">MC</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">HairLine</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">Anodizing</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">Assembly</a>
                      </li>-->
                      <li class="nav-item">
                        <a class="nav-link" href="/main/generate_qr_download" target="_blank" id="generate_qr_link">Tạo mã QR</a>
                      </li>
                      <li class="nav-item">
                        <input class="nav-link" id="name_model" placeholder="Nhập mã model"></a>
                      </li>
                      <li class="nav-item">
                        <input class="nav-link" id="quantity" placeholder="Số lượng" type="number">
                      </li>
                    </ul>   
                    <div class="clock ml-3">
                        <h5 id="date-time"></h5>
                      </div> 
                  </div>
            </nav>   
    </header>
    <main id="main">
        {% block content %}{% endblock %}
    </main>
</body>
<script type="text/javascript">
  var socket = io.connect('http://' + document.domain + ':' + location.port);
  socket.on('refresh', function(msg) {
      window.location.reload();  // Làm mới trang khi có nội dung mới
  });
  document.getElementById('generate_qr_link').addEventListener('click', function (event) {
    const model = document.getElementById('name_model').value.trim();
    const quantity = document.getElementById('quantity').value.trim();

    if (model === '' || quantity === '') {
      alert('Vui lòng nhập đầy đủ model và số lượng!');
      event.preventDefault();
      return;
    }

    const url = `/main/generate_qr_download?model=${encodeURIComponent(model)}&quantity=${encodeURIComponent(quantity)}`;
    this.href = url;
  });
</script>
</html>

app/templates/qr_info.html
{% extends 'layout.html' %}

{% block title %}QR Code Information{% endblock %}

{% block content %}
    <h1>QRCode Infor</h1>
    <div class="container">
        <button class="cta" onclick="printQRcode()">
            <span class="hover-underline-animation">IN MÃ QR TẠI ĐÂY</span>
            <svg
              id="arrow-horizontal"
              xmlns="http://www.w3.org/2000/svg"
              width="30"
              height="10"
              viewBox="0 0 46 16"
            >
              <path
                id="Path_10"
                data-name="Path 10"
                d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z"
                transform="translate(30)"
              ></path>
            </svg>
          </button>
    </div>
    <div class="qr-code">
        <p id="creation-time">Creation Time: {{ creation_time_str }}
          {% if model %}
            <p style="font-size: 22px;"><strong>📦 Model:</strong> {{ model }}</p>
          {% endif %}

          {% if quantity %}
            <p style="font-size: 22px;"><strong>🔢 Số lượng:</strong> {{ quantity }}</p>
          {% endif %}
        </p>
        <img id="qr_code" src="data:image/png;base64,{{ qr_image }}" alt="QR Code">
</div>
{% endblock %}

app/templates/scan_qr.html
{% extends 'layout.html' %}

{% block content %}
<div class="modal" tabindex="-1" role="dialog" id="messageModal" style="display:block;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="modalTh" class="modal-title">Thông báo: Thời gian tạo mã:<br> 🕒 {{creation_time_str}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modalMessage">
        <p style="font-size: 18px;">{{ message | safe }}</p>
        {% if model %}
          <p style="font-size: 22px;"><strong>📦 Item Status(상품 상태):</strong> {{ status }}</p>
        {% endif %}
        {% if model %}
          <p style="font-size: 22px;"><strong>📦 Model(모델):</strong> {{ model }}</p>
        {% endif %}
        {% if quantity %}
          <p style="font-size: 22px;"><strong>🔢 Số lượng(수량):</strong> {{ quantity }}</p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <a class="btn btn-secondary" href="/">Quay lại</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}